### ISSUE TITLE
Conversion is skipped when directly specifying a single output file

### ISSUE THREAD

**Issue by mu22le** [pgaskin/kepubify#72] opened 2021-09-29 20:01 UTC
Hi, I converted a few books from using kepubify, but I have noticed an odd behavior with my kobo Libra (fw 4.28.18220). If I exit the book-reading interface and open the book again, the page resets to the beginning of the chapter. 

I tried to get around this issue by creating a bookmark, but the bookmark too takes me back to the begging of the chapter, even though the bookmark page says that it is at (for instance) 25% of the chapter.

None of this happens with a kepub from the kobo store or one converted using calibre. 

I am using [KoboCloud](https://github.com/fsantini/KoboCloud) to transfer the files. For some reason, they all have ".epub.kepub" as extension.

**Comment by pgaskin** [comment] 2021-09-30 03:46
Can you email me one of the ebooks, or at least send me the content.opf file and a list of files within the book so I can take a look?

**Comment by mu22le** [comment] 2021-09-30 06:56
Hi Patrick,
Thanks for the prompt reply! While preparing to send you the files, I have realized that I made a mistake in the conversion process. The kepub file in my kobo is identical to the original epub file.

It looks like the -o option causes the files to be copied instead of converted; is this the intended behavior? My conversion command looks like this:

`kepubify "test.epub" -o "test.epub.kepub"`

**Comment by pgaskin** [comment] 2021-12-06 21:34
I'm going to close this issue since I haven't received a reply yet. Feel free to re-open it if needed.

**Closed by pgaskin** 2021-12-06 21:34 UTC
Labels: invalid

**Comment by mu22le** [comment] 2021-12-07 09:39
Hi, and sorry for not getting back to you sooner.

It seems to me that if the extension of the output file is not  `.kepub.epub` the file is copied, not converted. E.g.
```
./kepubify test.epub -o test.kepub
Kepubify v4.0.2

[  1/  1] Copying test.epub

1 total: 0 converted, 1 copied, 0 skipped, 0 errored
```
I imagine this is the intended behaviour, so I would only suggest tweaking the documentation text to avoid others falling into the same mistake I made. 

The current help text is:
```
  -o, --output string      [>1 inputs || 1 file input with existing dir output]: Directory to place converted files/dirs under; [1 file input with
                           nonexistent output]: Output filename; [1 dir input]: Output directory for contents of input (default: current directory)
```


I would go with something like:
```
  -o, --output string      [>1 inputs || 1 file input with existing dir output]: Directory to place converted files/dirs under; 
                           [1 file input with nonexistent output]: Output filename (extension must be .kepub.epub); 
                           [1 dir input]: Output directory for contents of input (default: current directory)
```
Apart from that, I agree the report can be closed.

**Comment by pgaskin** [comment] 2021-12-08 00:52
That is indeed the intended behaviour. I will update the documentation for the next version. I might also make `.kepub` work as an explicit extension even if `--calibre` isn't specified. Thanks for the feedback!

**Comment by karlb** [comment] 2022-10-09 11:45
> That is indeed the intended behaviour. I will update the documentation for the next version. I might also make `.kepub` work as an explicit extension even if `--calibre` isn't specified. Thanks for the feedback!

I still need the `--calibre` option in commands like `kepubify out/test.epub --calibre -o out/test.kepub` when using kepubify v4.0.4. To me, this is surprising behavior and the fix not obvious. So I would recommend to allow '.kepub' as an extension even without the `--calibre` option.

Thanks for this useful tool!
